### ISSUE TITLE
Bug: Clarification on dialog heading level 

### ISSUE THREAD

**Issue by MrHBS** [dequelabs/cauldron#1192]
### Steps to reproduce

[Deque University](https://dequeuniversity.com/library/aria/simple-dialog) uses h1 for the heading while this component library uses h2. I would like to understand why so.

### Expected Behavior

Heading level of dialog to be h1

### Actual Behavior

It defaults to h2

### Version

latest

### Anything else we should know?

Additional information

**Comment by scurker** [comment]
Hi @MrHBS, there's no official requirement that I can find that requires modal headings to start at `h1`, in fact the aria authoring practices guide example has their [modal dialog example](https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/examples/dialog/) heading level start at `h2`. We've just happen to choose starting at `h2` because we typically only have an `h1` at the very top of our pages.

If there is a need to customize your modal headings for whatever reason, the heading level can be customized with a specific object property:

```tsx
<Dialog heading={{ text: 'Heading', level: 1 }}>
  ...
</Dialog>
```
