### ISSUE TITLE
clickOutsideListener is broken on docs

### ISSUE THREAD

**Issue by scurker** [dequelabs/cauldron#67]

**Comment by Mottie** [comment]
I was looking at this problem today. If we change this line - https://github.com/dequelabs/cauldron/blob/master/packages/react/src/components/ClickOutsideListener/index.tsx#L38

```diff
- if (nodeRef && !nodeRef.contains(target)) {
+ if (target?.classList.contains('Scrim')) {
```

to test for the `Scrim` class name, it starts working, but I don't think this is the best solution:
- `nodeRef` would no longer be needed
- This forces a dependency on the `Scrim` component

Moving the `Scrim` component outside of the `ClickOutsideListener` in the `Dialog` component makes the `Scrim` component overlay the dialog.

Given these problems, I think it'd be better to discuss a better solution instead of me opening a PR that won't be used.

**Comment by okry** [comment]
Fixed
