### ISSUE TITLE
Escape doesn't close Dialogs/Modals

### ISSUE THREAD

**Issue by abbeyperini-deque** [dequelabs/cauldron#694]
If you use the toggle syntax shown in the docs, <kbd>escape</kbd> will not close a `<Dialog>`/`<Modal>` because `onClose` fires twice. The close button still works because `onClose` fires three times.

<kbd>escape</kbd> does not close the modals [on the docs site](https://cauldron.dequelabs.com/components/Modal) and I've replicated this in 4 `<Dialog>`s in the `feature-upgrade-cauldron` branch in `axe-mobile-client`.

Code for this screen recording:

```
toggleHelpModal = () => {
    console.log("toggle modal!")
    this.setState(({ showHelpModal }) => {
      return { showHelpModal: !showHelpModal };
    });
  };
```

```
<MenuItem onClick={toggleHelpModal} >
```

```
<Dialog
      show={props.showHelpModal}
      heading={{ text: "Help" }}
      onClose={props.toggleHelpModal}
      className="no-footer"
    >
```

Screen recording showing "toggle modal!" logged in the console once when the menu item is clicked, twice when I hit <kbd>escape</kbd> while the modal remains open, and three times when I hit the close button as the modal closes:

https://user-images.githubusercontent.com/99676396/178051629-e0820344-bf05-4d24-a577-dc85b51370e3.mov

**Comment by scurker** [comment]
This is tricky, `onClose` is being called twice because of the `show` state:

1. When <kbd>esc</kbd> is pressed, `onClose` gets called via `react-focus-trap` and with `escapeDeactivates`
2. In the parent component, a toggle function gets called that flips the `show` prop from `true` to `false`
3. In the dialog, there's a [`componentDidUpdate`](https://github.com/dequelabs/cauldron/blob/c21fc13b9ddbddaca79e8a7a943f8a3b10755b82/packages/react/src/components/Dialog/index.tsx#L75-L81) function that detects a `show` prop change from `true` to `false` triggering `onChange` being called again.
4. This causes `onClose` to be called again, flipping the `show` prop state back to `true`.

For the native `X` button click event, this happens 3 times:

1. On the initial button press
2. On focus trap deactivation
3. On prop change

For the dialog secondary button close, it happens 3 times:

1. Button calls the toggle function
2. On focus trap deactivation
3. On prop change

I think `onClose` being called multiple times is a potential design flaw. Ideally, it only gets called once per event but that means the modifying reactive `show` prop in the `componentDidUpdate` to call `onClose` would be a potential breaking change.
