### ISSUE TITLE
Tooltip arrow offset when zoomed

### ISSUE THREAD

**Issue by scurker** [dequelabs/cauldron#726]
![cauldron tooltip with arrow slightly offset from the edge of the tooltip border](https://user-images.githubusercontent.com/1062039/183112028-b8550ac2-b157-410a-a347-d8cc3d7bccac.png)

When the user zooms, it appears that the arrow pointing back to the targeted element is offset incorrect (I noticed this specifically at 125% or 175% zoom). The tooltip arrow should be inline with the borders of the tooltip.

**Comment by somaalapati** [comment]
@thuey Can you please provide some QA notes on how & where to test this?

**Comment by scurker** [comment]
@somaalapati Take a look at the screenshot above, the tooltip arrow is very slightly misaligned when zoomed or on some retina devices. The tooltip arrow should always be in line with the borders of the tooltip no matter the zoom/pixel device ratio.

**Comment by somaalapati** [comment]
@Keerthi-Penukonda Please test this.

**Comment by Keerthi-Penukonda** [comment]
This issue is fixed.

At 125% Zoom
![image](https://user-images.githubusercontent.com/40262884/187851220-b1c7684f-0c73-4014-bcc0-b37b6dadf5c7.png)

At 175% Zoom
![image](https://user-images.githubusercontent.com/40262884/187851373-7acaacb7-da2b-4058-8a4c-3969f9917575.png)

At 250% Zoom
![image](https://user-images.githubusercontent.com/40262884/187851505-8b99b931-cc2f-4ce8-ae90-11ca3604f754.png)
