### ISSUE TITLE
Define a breaking change

### ISSUE THREAD

**Issue by dequejosie** [dequelabs/cauldron#881]
# What is a Breaking Change?

Cauldron provides a public API that consists of two parts, React components and CSS styles, each of which has its own package. In principle, any change to these two parts of API that is backward incompatible should be marked as a breaking change, and we should increment the major version number whenever a breaking change takes place (see [Semantic Versioning Specification (SemVer)](https://semver.org/)).

However there is a debate on whether to mark as breaking certain changes to Cauldron CSS styles with no visual impact (such as removing or renaming a classname), or whether to increment the major version number assuming that those CSS styles changes are breaking. There are a few reasons behind the hesitance to mark these changes as breaking and bump the major version:

1. we might break our API too frequently and that would decrease Cauldron's stability and risk fatiguing our users

2. we assume that the majority of Cauldron users do not consume CSS styles separately from their React components (although we allow our users to do so)

3. we have not been marking the changes to remove or rename a classname as breaking

The counterpoint to the first concern is that major version numbers are not sacred, as the creator of `SemVer` spec [defends releasing a new major version only about one month after the previous one](https://tom.preston-werner.com/2022/05/23/major-version-numbers-are-not-sacred.html). The proponents of `SemVer` spec also point out that we do not have any data to show how exactly our users utilize Cauldron. Therefore the second assumption could be right, but we have no proof for it and we have no control over how our users consume Cauldron. The last point is dictated by how we agree on the first two.

One key to the debate is whether we would want to (or continue to) support the consumption of Cauldron CSS styles separately from Cauldron React components, although that was the original intention for Cauldron. The following definitions and examples of breaking and non-breaking changes are based on the original intention. At the same time, the notes explore different scenarios if we decide against the original intention.

## Cauldron React components: breaking changes

1. Remove, replace, rename a component, as well as modify the relations between components

   - renamed Panel to IssuePanel
   - TabPanels are no longer TabList's children

2. Add, remove, replace, or rename required properties of a React component

   - removes the light/dark variant options for IconButton and TopBar.
   - The panel implementation has been replaced, including removing props that are not used in the new implementation
   - Loader component now set role, aria-valuetext, aria-busy, aria-valuemin, and aria-valuemax instead of making a generic role (div) have an aria-label

3. Modify the elements of which a React component consists, such as HTML tags and properties
   - selects now have parity with `<TextField />`s in that they always render an .Error div. This causes a slight layout difference with more space below each `<Select />`. The text "Required" will now show up with any `<Select />` who is passed a true required prop
   - topbar no longer renders role=menubar. New component `<MenuBar />` must now be used if menubar is desired
   - The api for for implementing a tooltip has changed. Instead of `<Tooltip><button /><Tooltip>`, the tooltip takes a target ref or html element. (This is a combination of breaking change #2 and #3)

## Cauldron CSS styles: breaking changes

1. Remove or rename a CSS classname

2. Change the value of a CSS classname that results in visual difference (see examples in [Visual Breaking Change in Design Systems](https://medium.com/eightshapes-llc/visual-breaking-change-in-design-systems-1e9109fac9c4))

   **Note**: if we decide not to support the consumption of CSS styles separately from the React components, then we should at least mark the shared classnames as breaking (`packages/styles/variables`)

## What is not a Breaking Change?

1. Add a React component or CSS classname

2. Add optional properties to a React component

3. Change the value of a CSS classname that does not result in visual difference

4. Change the areas that are not a part of Cauldron's public API, such as docs, demos, and tests

**Comment by scurker** [comment]
Thank you for this @dequejosie, this is a great start!

> Remove or rename a CSS classname

I want to discuss this a little bit more because I think we need to take into account for whom and what we are building cauldron for. The documentation makes no mention of using styles/classes in isolation, and I don't foresee us realistically supporting that use case, making me lean towards the intended usage of cauldron is in conjunction with the react components.

Cauldron's primary purpose is to help us at Deque have a consistent user experience with a common design language, the fact that we publish it publicly is just an additional bonus - but I strongly believe given our limited resources and the primary focus we should try to limit the things we do and don't officially support, with this instance where changing a class name in isolation would not be a breaking change.

There's also a little bit of nuance here - if we were to consider these changes a breaking change it's only a breaking change _if_ the prior change was released.

> Change the value of a CSS classname that results in visual difference (see examples in [Visual Breaking Change in Design Systems](https://medium.com/eightshapes-llc/visual-breaking-change-in-design-systems-1e9109fac9c4))

I think we should try be more specific here if we can of some things we might consider a visual breaking change. We might could describe specific patterns that would be considered a breaking change or have a team review specific things. For example, assuming that applications are adhering to responsive designs correctly change a text size might not be a breaking change, while changing the background might be more likely to break accessibility.

Also as a whole I think we should try to consider avoiding breaking changes at all possible and include recommendations on alternatives. If we're changing the exported name of a component or a component's property, is it necessary to remove the old name? Same thing for css variables, and other things that might be used.

> Modify the elements of which a React component consists, such as HTML tags and properties

I'm a little confused with the examples here, are you saying that if a react component were to render an `<ol>` and is now rendering a `<ul>` that would be a breaking change?

**Comment by dequejosie** [comment]
Thank you for all your feedback @scurker! I strongly agree that we should try to avoid breaking changes at all possible and we should make that a principle for this process. I will add a session to list alternatives to breaking changes.

> Remove or rename a CSS classname

If we are not support Cauldron CSS styles separately from React components, which makes sense given the reason you provided, this should not be a breaking change.

> Change the value of a CSS classname that results in visual difference (see examples in [Visual Breaking Change in Design Systems](https://medium.com/eightshapes-llc/visual-breaking-change-in-design-systems-1e9109fac9c4))

Yes, let's add the nuance that `if the prior change was released,` and I will add a session to make a list of patterns of breaking visual changes.

> Modify the elements of which a React component consists, such as HTML tags and properties

What I see in the examples are: 
1. `select` does not render a `.Error``div` anymore
2. `topbar` does not render `role=menubar` anymore
3. `Tooltip` takes a target ref or html element instead of a `button`
Please let me know if we could make this point more concrete.

**Comment by schne324** [comment]
> change a text size might not be a breaking change, while changing the background might be more likely to break accessibility.

Text size is a factor when it comes to color contrast requirements so I don't think we can make these kinds of generalizations. 

> The documentation makes no mention of using styles/classes in isolation, and I don't foresee us realistically supporting that use case, making me lean towards the intended usage of cauldron is in conjunction with the react components.

I agree that the 'intended usage" is using the react components but I strongly disagree with the notion that if you use our **public** API in a way the deviates from our (undocumented) intended usage then you have to suffer with unexpected breaking changes. 

The styles is literally its own package...to me that insinuates that it _could_ be used without the react components and applied to any other framework or "vanilla" html.  In addition, as a result of it being its own package, it can be independently installed and even has it's own page on npmjs: https://www.npmjs.com/package/@deque/cauldron-styles.

Because of all of this, I think any breaking change to CSS should be considered a breaking change in cauldron and major version bumps should happen as a result.

**Comment by stephenmathieson** [comment]
> The documentation makes no mention of using styles/classes in isolation, and I don't foresee us realistically supporting that use case, making me lean towards the intended usage of cauldron is in conjunction with the react components.

We **very frequently** use the `Link` class (not component) in walnut. Are you suggesting this isn't intended usage?

**Comment by stephenmathieson** [comment]
> Treat cauldron as more of a pre-release project and don't worry about cutting a "major release" until it stabilizes.

I'm good with this.

> Just focus on the API contract for breaking changes for now, since that's a lot more clear-cut, and don't worry about the "visual contract" as much. We can add to the standard gradually over time when someone complains about a breaking change not being marked.


Also good with this, as long as we consider CSS classes part of the API (*we* use them extensively, outside of React components).

> Create/use a robust, comprehensive standard for breaking changes.

Seems like overkill IMO.

**Comment by scurker** [comment]
> Text size is a factor when it comes to color contrast requirements so I don't think we can make these kinds of generalizations.

That's why I said "might". Making the text size larger would not break color contrast while changing a background color is indeterminate and more likely to break things. There's a lot of nuance to decide when something is breaking and why I do find it hard to determine when changing a css values is breaking/non-breaking.

I think what might help here is to try to better define the scope of variables (as it limits their usage). There are system-wide variables that are shared across the library (such as the ones in [`variables.css`](https://github.com/dequelabs/cauldron/blob/develop/packages/styles/variables.css)). Changing a name and/or value there is much more likely to break something systematically vs if we were to change a variable that is more local to a component.

> I agree that the 'intended usage" is using the react components but I strongly disagree with the notion that if you use our **public** API in a way the deviates from our (undocumented) intended usage then you have to suffer with unexpected breaking changes.

> The styles is literally its own package...to me that insinuates that it _could_ be used without the react components and applied to any other framework or "vanilla" html. In addition, as a result of it being its own package, it can be independently installed and even has it's own page on npmjs: https://www.npmjs.com/package/@deque/cauldron-styles.

The public api is whatever we decide we want to support. Just because it is it's own package independently available doesn't mean that we support it officially and commit to it being non-breaking. If we are saying yes, now we want to commit to this being a public api and will not break it going forward we at a minimum should:

* Document the support and usage of it independent of `cauldron-react`
* Make changes that are backwards compatible (when possible) until we decide we want to remove the deprecated thing

For the last point, I'd like to see us get to the point where we're not just arbitrarily making breaking changes as I believe that slows us down from the review process + implementation. An example of this would be if we were to rename an existing variable ,`--x-old` to `--x-new` we would keep both variables in place:

```css
/* deprecated variable, use --x-new */
--x-old: var(--x-new);
--x-new: value;
```

A similar concept could apply to classes:

```css
/* Link is deprecated, use BetterLink */
.Link,
.BetterLink {
  color: blue;
}
```

Why does this matter? Because if we're constantly breaking things we're locking out new features until the author consuming cauldron decides they also have time to implement the breaking change.

> Treat cauldron as more of a pre-release project and don't worry about cutting a "major release" until it stabilizes.

If this means we commit to no breaking changes for the immediate future (utilizing some of the above guidelines), I think this would be acceptable.

> Just focus on the API contract for breaking changes for now, since that's a lot more clear-cut, and don't worry about the "visual contract" as much. 

This is where I'm leaning, trying to define what is a visual breaking change is a grey area _unless_ that somehow negatively impacts accessibility.

**Comment by scurker** [comment]
It seems like the consensus is we want to include both Components and Styles as part of our supported api. In the long run we should consider also documenting how styles are used/installed (#682) but for now we can just make a note that styles w/o components is considered supported.

As such, I would like to propose that we add the following to our contributing guidelines to specify what we consider breaking changes and how we should offer a phased deprecation approach before actually releasing the breaking change:

> # Breaking Changes
>
> Cauldron is constantly evolving, and it's inevitable that breaking changes will need to be introduced. Before a breaking change is released, other alternatives should be considered and allow for a deprecation period before the breaking change is released.
>
> ## Components
>
> For cauldron's component library, any of the following would be considered breaking changes:
>
> * Renaming (exported name) or removing a Component
> * Changing a prop that would break usage of an existing component
> * Adding a new required prop to an existing component
>
> ## Styles
>
> For cauldron's styles library, any of the following would be considered breaking changes:
> 
> * Changing or removing a class name
> * Changing or removing a global variable (see `variables.css`)
> * Changing or removing a component variables
> 
> In addition, changing a css property may be a breaking change for the following:
> 
> * Changing a global variable property (see `variables.css`)
> * Changing a component variable property
> 
> For the latter, the change must be reviewed by a member of the cauldron team to ensure there are no breaking changes.
> 
> ## Deprecating
> 
> Before a breaking change can be released, the breaking change should be documented with the component, property, or style being changed getting flagged as _Deprecated_. This could meaning warning the consumer that a component or property is now deprecated, or including a deprecated comment next to a css class name. This deprecation must exist for at least two months.
> 
> ## Removal
> 
> Once the deprecation period has passed, the breaking change can be implemented by removing the deprecation and including `BREAKING CHANGE:` in the body of your commit message with the description of the breaking change.
